# This rule is not used by the project kube-billing itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to billing.cloud-native.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-billing
    app.kubernetes.io/managed-by: kustomize
  name: billingplan-viewer-role
rules:
- apiGroups:
  - billing.cloud-native.io
  resources:
  - billingplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - billing.cloud-native.io
  resources:
  - billingplans/status
  verbs:
  - get
