---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - billing.cloud-native.io
  resources:
  - billingplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - billing.cloud-native.io
  resources:
  - billingplans/status
  - subscriptions/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - billing.cloud-native.io
  resources:
  - subscriptions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - billing.cloud-native.io
  resources:
  - subscriptions/finalizers
  verbs:
  - update
