apiVersion: billing.cloud-native.io/v1alpha1
kind: BillingPlan
metadata:
  labels:
    app.kubernetes.io/name: kube-billing
    app.kubernetes.io/managed-by: kustomize
  name: billingplan-sample
spec:
  # TODO(user): Add fields here
